// ChatContextKind will be generated by graphql-codegen once migration 076 is
// applied to the database. Until then we use a local alias.
export type ChatContextKind = "need" | "resource" | "NEED" | "RESOURCE";

/**
 * Build the URL used to navigate to a specific conversation thread from
 * the chat workspace. The thread is displayed inside `/chat` using URL
 * query parameters so the list and thread can be shown side-by-side on
 * wider viewports.
 */
export function conversationThreadUrl(kind: ChatContextKind, conversationId: string): string {
  return `/chat?kind=${kind}&id=${conversationId}`;
}

/**
 * Build the URL for the context entity (need or resource) linked from a
 * conversation header. Used for the "back-to-context" navigation link.
 */
export function conversationContextUrl(kind: ChatContextKind, contextId: string): string {
  const normalized = kind.toLowerCase();
  if (normalized === "need") {
    return `/needs/${contextId}`;
  }
  return `/resources/${contextId}`;
}
