// ChatContextKind will be generated by graphql-codegen once migration 076 is
// applied to the database. Until then we use a local alias.
export type ChatContextKind = "need" | "resource" | "NEED" | "RESOURCE";

/**
 * Build the URL used to navigate to a specific conversation thread from
 * the chat workspace. The thread is displayed inside `/chat` using URL
 * query parameters so the list and thread can be shown side-by-side on
 * wider viewports.
 */
export function conversationThreadUrl(kind: ChatContextKind, conversationId: string): string {
  return `/chat?kind=${kind}&id=${conversationId}`;
}

/**
 * Build the URL used to open a draft chat thread before a
 * conversation exists. The real conversation is created on first message send.
 */
export function conversationDraftUrl(params: {
  kind: "need" | "resource";
  contextId: string;
  otherAccountId?: string | null;
  title?: string | null;
}): string {
  const query = new URLSearchParams({
    kind: params.kind,
    draft: "1",
    contextId: params.contextId
  });

  if (params.otherAccountId?.trim()) {
    query.set("otherAccountId", params.otherAccountId.trim());
  }

  if (params.title?.trim()) {
    query.set("title", params.title.trim());
  }

  return `/chat?${query.toString()}`;
}

export function conversationDraftResourceUrl(params: {
  resourceId: string;
  otherAccountId: string;
  title?: string | null;
}): string {
  return conversationDraftUrl({
    kind: "resource",
    contextId: params.resourceId,
    otherAccountId: params.otherAccountId,
    title: params.title
  });
}

export function conversationDraftNeedUrl(params: {
  needId: string;
  title?: string | null;
}): string {
  return conversationDraftUrl({
    kind: "need",
    contextId: params.needId,
    title: params.title
  });
}

/**
 * Build the URL for the context entity (need or resource) linked from a
 * conversation header. Used for the "back-to-context" navigation link.
 */
export function conversationContextUrl(kind: ChatContextKind, contextId: string): string {
  const normalized = kind.toLowerCase();
  if (normalized === "need") {
    return `/needs/${contextId}`;
  }
  return `/resources/${contextId}`;
}

/**
 * Build the URL to the other participant's public account page.
 * Used for the participant navigation link in the conversation header.
 */
export function conversationParticipantUrl(accountId: string): string {
  return `/accounts/${accountId}`;
}
